# Generated by Django 3.0.5 on 2020-09-28 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.CharField(default='uncategorized', max_length=100),
        ),
    ]
