# Generated by Django 3.1.2 on 2020-11-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='updates',
            name='title',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
