# Generated by Django 3.1.1 on 2021-01-09 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_pastevents'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.ImageField(default='blog.jpg', upload_to='blog-img'),
        ),
    ]
